default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: None
  pool: 5
development:
  <<: *default
  database: glmrvn_development
test:
  <<: *default
  database: glmrvn_test
